/**
 * Import products from Mercado Libre Chile API into Supabase.
 * Usage: pnpm import-ml
 */

import * as dotenv from 'dotenv'
import * as path from 'path'
import { createClient } from '@supabase/supabase-js'

// Load .env.local
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

// ─── Config ───────────────────────────────────────────────────────────────────

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY)

const ML_ACCESS_TOKEN = process.env.ML_ACCESS_TOKEN ?? ''

if (!ML_ACCESS_TOKEN) {
  console.warn('⚠ ML_ACCESS_TOKEN no está definido en .env.local — las requests irán sin Authorization\n')
} else {
  console.log(`✓ ML_ACCESS_TOKEN cargado (${ML_ACCESS_TOKEN.slice(0, 8)}...)\n`)
}

const CATEGORIES = [
  { query: 'audifonos',  slug: 'audio',      name: 'Audio' },
  { query: 'smartphone', slug: 'tecnologia', name: 'Celulares' },
  { query: 'notebook',   slug: 'tecnologia', name: 'Computación' },
  { query: 'television', slug: 'tecnologia', name: 'Electrónica' },
]

const ML_SEARCH_URL = 'https://api.mercadolibre.com/sites/MLC/search'
const DELAY_MS = 200

// ─── Types ────────────────────────────────────────────────────────────────────

type MLItem = {
  id: string
  title: string
  price: number
  currency_id: string
  thumbnail: string
  permalink: string
  attributes: Array<{ id: string; value_name: string | null }>
}

type MLSearchResponse = {
  results: MLItem[]
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function extractBrand(item: MLItem): string | null {
  const attr = item.attributes.find((a) => a.id === 'BRAND')
  return attr?.value_name ?? null
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function run() {
  console.log('=== Revius — Importador Mercado Libre Chile ===\n')

  // Lookup store_id for 'mercado-libre'
  const { data: mlStore } = await supabase
    .from('stores')
    .select('id')
    .eq('slug', 'mercado-libre')
    .single()

  if (!mlStore) {
    console.warn("Store 'mercado-libre' not found in public.stores — product_sources will skip store_id")
  }
  const storeId: string | null = mlStore?.id ?? null

  const summary: Record<string, { inserted: number; skipped: number; errors: number }> = {}

  for (const cat of CATEGORIES) {
    console.log(`\n▶ Fetching category: ${cat.name} (q=${cat.query})`)

    // Get category_id from public.categories
    const { data: categoryRow } = await supabase
      .from('categories')
      .select('id')
      .eq('slug', cat.slug)
      .single()

    if (!categoryRow) {
      console.warn(`  ⚠ Category slug '${cat.slug}' not found in public.categories — skipping`)
      summary[cat.name] = { inserted: 0, skipped: 0, errors: 1 }
      continue
    }

    // Fetch from ML API
    let items: MLItem[] = []
    try {
      const url = `${ML_SEARCH_URL}?q=${encodeURIComponent(cat.query)}&limit=50`
      const headers: Record<string, string> = {
        'User-Agent': 'Mozilla/5.0 (compatible; Revius/1.0)',
      }
      if (ML_ACCESS_TOKEN) headers['Authorization'] = `Bearer ${ML_ACCESS_TOKEN}`

      const res = await fetch(url, { headers })
      if (!res.ok) {
        const body = await res.text()
        throw new Error(`HTTP ${res.status} — ${body.slice(0, 200)}`)
      }
      const json = (await res.json()) as MLSearchResponse
      items = json.results ?? []
      console.log(`  ✓ Got ${items.length} items from ML API`)
    } catch (err) {
      console.error(`  ✗ ML API error for q=${cat.query}:`, err)
      summary[cat.name] = { inserted: 0, skipped: 0, errors: 1 }
      continue
    }

    let inserted = 0
    let skipped = 0
    let errors = 0

    for (const item of items) {
      const brand = extractBrand(item)

      // Upsert into products (slug is auto-generated by trigger on insert,
      // on conflict we update name/brand/image_url to keep data fresh)
      const { data: product, error: productError } = await supabase
        .from('products')
        .upsert(
          {
            name: item.title,
            brand,
            image_url: item.thumbnail.replace(/^http:/, 'https:'),
            category_id: categoryRow.id,
          },
          { onConflict: 'slug', ignoreDuplicates: false },
        )
        .select('id')
        .single()

      if (productError || !product) {
        console.error(`  ✗ Insert product failed [${item.title}]:`, productError?.message)
        errors++
        await delay(DELAY_MS)
        continue
      }

      // Upsert into product_sources
      const { error: sourceError } = await supabase
        .from('product_sources')
        .upsert(
          {
            product_id: product.id,
            store_id: storeId,
            store_name: 'Mercado Libre',
            price: item.price,
            currency: item.currency_id,
            in_stock: true,
            url: item.permalink,
          },
          { onConflict: 'product_id,store_name', ignoreDuplicates: false },
        )

      if (sourceError) {
        console.error(`  ✗ Insert source failed [${item.title}]:`, sourceError.message)
        errors++
      } else {
        inserted++
      }

      await delay(DELAY_MS)
    }

    summary[cat.name] = { inserted, skipped, errors }
    console.log(`  → ${cat.name}: ${inserted} insertados, ${errors} errores`)
  }

  // ─── Summary ──────────────────────────────────────────────────────────────
  console.log('\n=== Resumen ===')
  let total = 0
  for (const [cat, stats] of Object.entries(summary)) {
    console.log(`  ${cat}: ${stats.inserted} productos  |  ${stats.errors} errores`)
    total += stats.inserted
  }
  console.log(`\n  Total importados: ${total}`)
}

run().catch((err) => {
  console.error('\nError fatal:', err)
  process.exit(1)
})
